version: '2.1'

services:
  nodecrawl:
    image: nodecrawl
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    ## set your startup file here
    command: npm run prod